Add examples for using Markers
mapbox/mapbox-react-examples pull request #15
Opened 2021-03-07 21:09 UTC by rahsheen

Ran into someone struggling with this and also noticed there's issue #14  so attempted to fill this gap with a few examples based on the official docs.

2022-03-10 08:30 UTC, Bill0197 approved these changes

2022-05-29 14:06 UTC, rahsheen commented
Any reason this cannot be merged?

2022-05-30 15:27 UTC, tristen requested changes
Thanks for the PR! These look great. I just left a few comments on a couple of things I saw that should be updated before merging.

2022-05-30 15:27 UTC, tristen commented on markers-custom/src/Map.js
> +        </div>
For simplicity, can you drop this feature and logic above from your marker examples as it's not related?

2022-05-30 15:27 UTC, tristen commented on markers-custom/src/App.js
> +    </div>
Nit picky but this probably doesn't need to be wrapped in div tags?

2022-05-30 15:27 UTC, tristen commented on markers-custom/src/Map.js
> +    <div>
Intead of an extra wrapping div, could you use empty tag [framents](https://reactjs.org/docs/fragments.html#short-syntax)?

2022-05-30 15:27 UTC, tristen commented on markers-custom/README.md
> +Runs the app from http://localhost:3000
Can you update the READMEs of the three examples to reflect what they do? No need to include a visual example and these can be pretty short.

2022-05-30 15:27 UTC, tristen commented on markers-custom/package.json
> +  "name": "basic",
Can you update the name field here to the directory name of your examples?

2022-06-18 03:11 UTC, rahsheen commented
Sounds good. Implemented the suggestions. Thanks!

2022-06-20 13:38 UTC, tristen approved these changes
Looks great!

2022-06-20 13:38 UTC, merged